services:
  mwgg-account-server:
    image: mouthwashgg-account-server
    build:
      context: ./account-server
      dockerfile: ./Dockerfile
    networks:
      - app
    ports:
      - 8000:8000/tcp
    env_file:
      - ./account-server/.env

networks:
  app:
    external:
      name: mwgg_app